module.exports = [
    '/help - this list',
    '',
    '/app_log - print forever log',
    '',
    '/apt_update - check for updates',
    '/apt_upgrade - install updates',
    '',
    '/dns_update - update dns filter',
    '',
    '/pi_reboot - reboot pi',
    '/pi_shutdown - shutdown pi',
    '',
    '/ufw_log - get ufw logs',
    '/ufw_clean - clean system log',
];
