module.exports = [
    '/help - this list',
    '',
    '/app_log - print forever log',
    '',
    '/apt_update - check for updates',
    '/apt_upgrade - install updates',
    '',
    '/bal_update - update balance data',
    '',
    '/dns_check - check whitelisted hosts at dns filter',
    '/dns_query - query dns filter',
    '/dns_update - update dns filter',
    '',
    '/mus_unavail - find unavailable tracks in playlist',
    '/mus_dups - find duplicate tracks in playlist',
    '',
    '/pi_reboot - reboot pi',
    '/pi_shutdown - shutdown pi',
    '',
    '/ufw_log - get ufw logs',
    '/ufw_clean - clean system log',
];
